"""add pizzas

Revision ID: 5c2d33730f79
Revises: efdb08c3a38d
Create Date: 2025-01-27 10:57:45.265029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2d33730f79'
down_revision = 'efdb08c3a38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizzas_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size_in_inches', sa.Integer(), nullable=True),
    sa.Column('crust', sa.String(), nullable=True),
    sa.Column('meta_pizza', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizzas_table')
    # ### end Alembic commands ###
