"""add kosher column

Revision ID: efdb08c3a38d
Revises: fd4aa53beb40
Create Date: 2025-01-27 10:43:07.942464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdb08c3a38d'
down_revision = 'fd4aa53beb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deli_sandwiches_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_kosher', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deli_sandwiches_table', schema=None) as batch_op:
        batch_op.drop_column('is_kosher')

    # ### end Alembic commands ###
